# Definición del problema

Se desea entrenar un modelo que sea capaz de 'completar' una palabra a medio escribir, o proponer una corrección para una palabra ya escrita en caso de que la misma se encuentre mal escrita.

Se utilizará un algoritmo de 'hallar la palabra incorrecta' para determinar si una palabra está escrita incorrectamente, de acuerdo a un lexicón construido con palabras extraídas de la página web de la RAE (disponible en https://github.com/JorgeDuenasLerin/diccionario-espanol-txt, actualizado en Mayo 2024)

Además, se construirá una matriz de probabilidad con las palabras extraídas para que las recomendaciones de completado y corrección se realicen en función de la frecuencia de utilización de las palabras. El sistema será capaz de realizar estas funciones en Español.

Se utilizarán textos para entrenarlo.

# Estructura del modelo

# Importacion de Librerias

In [ ]:
import numpy as np

import keras as kr
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

# Datos de entrada

In [ ]:
# Extract text from Spanish book converted into txt format
txt_file = "text_dump.txt"

lines: list[str] = []
with open(txt_file, 'r', encoding="UTF-8") as file:
  for line in file:
    if line != "\n": #Do not include empty lines in text digest
      lines.append(line)

#As of this point, 'lines' variable should hold the full length of the txt file
print("Total line count:", len(lines))
print("Total character count:", sum([len(item) for item in lines]))

Total line count: 778
Total character count: 78701


In [ ]:
# Extract used vocabulary and construct encode/decode dictionaries
full_txt_str: str = ""
vocab: list[str] = []
acc = 0 #Used to print partial progress of the operation
big_acc = 1 #Same as above
for paragraph in lines[31:14346]: #Do not consider index, acknowledgements, appendix, etc etc (i.e. only consider main story block for training)
  full_txt_str += paragraph
  for char in paragraph:
    if char not in vocab:
      vocab.append(char)
  #Print partial progress
  acc += 1
  if (acc >= (14346-31)*0.2):
    print(f"Vocabulary {20*big_acc}% built")
    acc = 0
    big_acc += 1
vocab.sort()
vocab_size = len(vocab)

encode_keys:dict[str,int] = {}
decode_keys: dict[int, str] = {}
for index, char in enumerate(vocab):
  encode_keys[char] = index
  decode_keys[index] = char

#As of this point, the full vocabulary should be indexed
print("Total unique characters:", vocab_size)
print("Total encode/decode dictionary keys:", len(encode_keys.keys()),"|", len(decode_keys.keys()))
print("Key list\n",encode_keys.keys())

Total unique characters: 87
Total encode/decode dictionary keys: 87 | 87
Key list
 dict_keys(['\n', ' ', '!', '"', '(', ')', ',', '-', '.', '/', '0', '1', '2', '3', '5', '6', '7', '8', '9', ':', ';', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '¡', '¿', 'Á', 'Ú', 'á', 'é', 'í', 'ñ', 'ó', 'ú', 'ü', '—', '“', '”', '…'])


In [ ]:
# Construct input/output data for LSTM network
seq_length = 50
input_seqs: list[list[float]] = []
output_seqs: list[float] = []
acc = 0 #Used to print partial progress of the operation
big_acc = 1 #Same as above

current:list[float] = []
for char in full_txt_str:
  if (len(current) >= seq_length):
    input_seqs.append(current.copy())
    output_seqs.append(encode_keys[char])
    current = current[1:] #Remove first element
  current.append(encode_keys[char])
  #Print partial progress
  acc += 1
  if (acc >= len(full_txt_str)*0.2):
    print(f"IO data {20*big_acc}% built")
    acc = 0
    big_acc += 1

#Normalize input sequences
normal_input_seqs: list[list[float]] = []
for row in input_seqs:
  normal_input_seqs.append([item/(vocab_size - 1) for item in row])
print("Data normalization done")

#Construct arrays from data used
train_data: np.ndarray = np.array([np.array(row) for row in normal_input_seqs])
train_tags: np.ndarray = np.array([np.zeros(vocab_size) for item in output_seqs])
for index, value in enumerate(output_seqs):
  train_tags[index][value] = 1.0

#As of this point, the full set of training data has been built
print("Train shape:", train_data.shape)
print("Tags shape:", train_tags.shape)
print("First 20 steps")
acc = 0
for data,tag in zip(train_data, train_tags):
  print(acc+1)
  print(data)
  print(tag)
  acc += 1
  if (acc >= 20):
    break

IO data 20% built
IO data 40% built
IO data 60% built
IO data 80% built
IO data 100% built
Data normalization done
Train shape: (73835, 5)
Tags shape: (73835, 87)
First 20 steps
1
[0.96511628 0.8372093  0.43023256 0.69767442 0.73255814]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2
[0.8372093  0.43023256 0.69767442 0.73255814 0.01162791]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3
[0.43023256 0.69767442 0.73255814 0.01162791 0.60465116]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

# Construcción del modelo

In [ ]:
filename = "savestate.keras"
isNew = True

vect_model = None
if (isNew):
  vect_model = Sequential()
  vect_model.add(kr.Input(shape=(seq_length,1)))
  vect_model.add(LSTM(256)) #Add dropout?
  vect_model.add(Dropout(0.2))
  vect_model.add(Dense(vocab_size, activation="softmax"))
  vect_model.compile(loss="categorical_crossentropy",optimizer="rmsprop")
else:
  kr.models.load_model(filename)

# Entrenamiento del modelo

In [75]:
epoch_ct:int = 0
train_length:int = 200

predict:kr.History = vect_model.fit(train_data, train_tags, batch_size = 64,epochs = train_length)
epoch_ct += train_length
state_filename = "state_" + str(epoch_ct) + "_28Nov.keras"
vect_model.save(state_filename)

Epoch 1/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5585 - loss: 1.3584
Epoch 2/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5596 - loss: 1.3606
Epoch 3/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.5584 - loss: 1.3603
Epoch 4/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5556 - loss: 1.3682
Epoch 5/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5591 - loss: 1.3610
Epoch 6/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5580 - loss: 1.3586
Epoch 7/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5606 - loss: 1.3559
Epoch 8/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5568 - loss: 1.3690
Epoch 9/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5586 - loss: 1.3659
Epoch 10/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5564 - loss: 1.3621
Epoch 11/200
1154/1154 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5539 - loss: 1.3706
Epoch 12/200
1154/1

# Evaluación

In [76]:
seed = "princ"
result = seed
seed_data = [encode_keys[char]/(vocab_size - 1) for char in seed]
for i in range(20):
  predict_data = np.reshape(np.array(seed_data), (1, len(seed_data), 1))
  prediction = vect_model.predict(predict_data)

  index = np.argmax(prediction)
  next_char = decode_keys[index]
  result += next_char
  print("NEXT",index,next_char,sep="|")

  seed_data.append(encode_keys[char]/(vocab_size - 1))
  seed_data = seed_data[1:] #Remove first element to move window along sequence

  if ( (next_char == " ")or(next_char == "\n") ):
    break

print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|55|i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NEXT|70|y
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
NEXT|8|.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NEXT|2|!
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
NEXT|47|a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
NEXT|47|a
princiy.!aaaaaaaaaaaaaaaa
